#!/usr/bin/env bash
# Deploy secrets from environment variables to secrets.yaml
set -euo pipefail

CONFIG_DIR="${CONFIG_DIR:-config}"
SECRETS_FILE="${CONFIG_DIR}/secrets.yaml"

echo "[secrets] Generating secrets.yaml from environment variables..."

# Check if any Strava secrets are set
if [[ -z "${STRAVA_CLIENT_ID:-}" ]] && [[ -z "${STRAVA_CLIENT_SECRET:-}" ]]; then
    echo "[secrets] No Strava credentials found in environment"
    echo "[secrets] Skipping secrets.yaml generation"
    exit 0
fi

# Create/update secrets.yaml
cat > "${SECRETS_FILE}" << EOF
# ============================================================================
# SECRETS - Auto-generated from GitHub Secrets
# ============================================================================
# DO NOT edit this file manually when using GitHub Actions deployment
# Add secrets via: GitHub → Repository Settings → Secrets and variables → Actions
# ============================================================================

EOF

# Add Strava credentials if present
if [[ -n "${STRAVA_CLIENT_ID:-}" ]] && [[ -n "${STRAVA_CLIENT_SECRET:-}" ]]; then
    cat >> "${SECRETS_FILE}" << EOF
# ----------------------------------------------------------------------------
# STRAVA COACH
# ----------------------------------------------------------------------------
strava_client_id: "${STRAVA_CLIENT_ID}"
strava_client_secret: "${STRAVA_CLIENT_SECRET}"

EOF
    echo "[secrets] ✓ Added Strava credentials"
fi

# Add other secrets as needed (examples below)
if [[ -n "${TUYA_CLIENT_ID:-}" ]]; then
    cat >> "${SECRETS_FILE}" << EOF
# ----------------------------------------------------------------------------
# TUYA
# ----------------------------------------------------------------------------
tuya_client_id: "${TUYA_CLIENT_ID}"
tuya_client_secret: "${TUYA_CLIENT_SECRET:-}"
tuya_user_id: "${TUYA_USER_ID:-}"

EOF
    echo "[secrets] ✓ Added Tuya credentials"
fi

if [[ -n "${MQTT_BROKER:-}" ]]; then
    cat >> "${SECRETS_FILE}" << EOF
# ----------------------------------------------------------------------------
# MQTT
# ----------------------------------------------------------------------------
mqtt_broker: "${MQTT_BROKER}"
mqtt_port: ${MQTT_PORT:-1883}
mqtt_username: "${MQTT_USERNAME:-}"
mqtt_password: "${MQTT_PASSWORD:-}"

EOF
    echo "[secrets] ✓ Added MQTT configuration"
fi

# Set proper permissions
chmod 600 "${SECRETS_FILE}"

echo "[secrets] Generated ${SECRETS_FILE}"
echo "[secrets] File contains $(grep -c ":" "${SECRETS_FILE}") secret entries"
